GTCEuStartupEvents.registry('gtceu:material', event => {
    event.create('uranyl_sulfate')
    .liquid()
    .color(0xFFA500)

    event.create('uranyl_carbonate')
    .liquid()

    event.create('magnesium_sulphate')
        .dust()
        .liquid()
        .components("1x magnesium" , "1x sulfur" , "4x oxygen")

    event.create('enriched_impure_uranyl_solution')
        .liquid()

    event.create('tributyl_phosphate')
        .liquid()
    event.create('sinter')
        .dust()
        .color(0xff2a00)
    event.create('ranyl_nitrate_solution_compound')
        .liquid().color(0xff9200)
    event.create('ammonium_diuranate')
        .dust().color(0x0bfe1c)
    event.create('triuranium_octoxide')
        .dust().color(0xd7edd9)
    event.create('sodium_aluminum_oxide')
        .liquid().color(0x0055ff)
    event.create('bauxite_residue')
        .dust(0xe500ff)
    event.create('aluminium_hydroxide')
        .dust().color(0x1101ff)
    event.create('alumina')
        .dust()
        .components('2x aluminium' , '3x oxygen')
    event.create('fluoaluminic_acid')
        .liquid().color(0x48b35f)
    event.create('aluminium_sulfate')
        .liquid().color(0x0006ff)
    event.create('dilute_trichlorosilane')
        .liquid().color(0x00f6ff)
    event.create('trichlorosilane')
        .liquid().color(0x00f6ff)
    event.create('depleted_reactor_uranium_simple_liquid')
        .liquid()
        .color(0x56915a)
    event.create('metallurgical_grade_silica_fume')
        .dust()
        .color(0xfedb24)
})
GTCEuStartupEvents.materialModification(() => {
    GTMaterials.get("uranyl_sulfate").setFormula("UO₂SO₄")
    GTMaterials.get("uranyl_carbonate").setFormula("UO₂CO₃")
    GTMaterials.get("tributyl_phosphate").setFormula("(C₄H₉)₃PO₄")
    //GTMaterials.get("uranyl_nitrate_solution_compound").setFormula("UO₂(NO₃)₂·TBP")
    GTMaterials.get("ammonium_diuranate").setFormula("(NH₄)₂U₂O₇")
    GTMaterials.get("triuranium_octoxide").setFormula("U₃O₈")
    GTMaterials.get("sodium_aluminum_oxide").setFormula("NaAl(OH)₄")
    GTMaterials.get("aluminium_hydroxide").setFormula("Al(OH)₃")
    GTMaterials.get("fluoaluminic_acid").setFormula("H₃AlF₆")
    GTMaterials.get("aluminium_sulfate").setFormula("Al₂(SO₄)₃")
    GTMaterials.get("dilute_trichlorosilane").setFormula("SiHCl₃")
    GTMaterials.get("trichlorosilane").setFormula("SiHCl₃")
})