GTCEuStartupEvents.registry('gtceu:material', event => {
    event.create('uranyl_sulfate')
    .liquid()
    .color(0xFFA500)

    event.create('uranyl_carbonate')
    .liquid()

    event.create('magnesium_sulphate')
        .dust()
        .liquid()
        .components("1x magnesium" , "1x sulfur" , "4x oxygen")

    event.create('enriched_impure_uranyl_solution')
        .liquid()
        .color(0xfe52e2)
    event.create('tributyl_phosphate')
        .liquid()
        .color(0xec13d2)
    event.create('sinter')
        .dust()
        .color(0xff2a00)
    event.create('ranyl_nitrate_solution_compound')
        .liquid().color(0xff9200)
    event.create('ammonium_diuranate')
        .dust().color(0x0bfe1c)
    event.create('triuranium_octoxide')
        .dust().color(0xd7edd9)
    event.create('sodium_aluminum_oxide')
        .liquid().color(0x0055ff)
    event.create('bauxite_residue')
        .dust(0xe500ff)
    event.create('aluminium_hydroxide')
        .dust().color(0x1101ff)
    event.create('alumina')
        .dust()
        .components('2x aluminium' , '3x oxygen')
    event.create('fluoaluminic_acid')
        .liquid().color(0x48b35f)
    event.create('aluminium_sulfate')
        .liquid().color(0x0006ff)
    event.create('dilute_trichlorosilane')
        .liquid().color(0x00f6ff)
    event.create('trichlorosilane')
        .liquid().color(0x00f6ff)
    event.create('depleted_reactor_uranium_simple_liquid')
        .liquid()
        .color(0x56915a)
    event.create('metallurgical_grade_silica_fume')
        .dust()
        .color(0xfedb24)
    event.create('tbp_kerosene_extractant') //TBP煤油萃取剂
        .liquid()
        .color(0x0a95ff)
    event.create('organic_phase_solution_containing_tetravalent_plutonium') //四价含钚有机相溶液
        .liquid()
        .color(0xe5df68)
    event.create('residual_aqueous_phase_mixed_solution') //残余水相混合溶液
        .liquid()
        .color(0xc70dff)
    event.create('uranyl_nitrate_solution_compound') //硝酸铀酰溶液化合物
        .liquid()
        .color(0x55df9b)
    event.create('aqueous_reduction_extraction_solution')//水性还原萃取溶液
        .liquid()
        .color(0x276c70)
    event.create('plutonium_containing_aqueous_solution') //含钚水相溶液
        .liquid()
        .color(0xffdd02)
    event.create('uranium_containing_oil_phase_solution')
        .liquid()
        .color(0x9466e6) //含铀油相溶液
    event.create('aqueous_reverse_extract')
        .liquid()
        .color(0xd57272) //水相反萃液
    event.create('uranium_containing_aqueous_solution')
        .liquid()
        .color(0x581845)
        //含铀水相溶液
    event.create('quaternary_plutonium_aqueous_solution')
        .liquid()
        .color('0x00ff4a')
        //四价含钚水相溶液
    event.create("multivalent_plutonium_solution")
        .liquid()
        .color(0xDAF7A6)//多价态含钚溶液
    event.create('oxalic_acid')
        .liquid()
        .color(0x18e69f)//草酸
    event.create('plutonium_oxalate_filter_cake')
        .dust()
        .color(0x59e52d)
    event.create('plutonium_dioxide')
        .dust()
        .color(0x4a88ef)
    event.create('h3no')
        .color(0xea1f1f)
        .liquid()
})
GTCEuStartupEvents.materialModification(() => {
    GTMaterials.get("uranyl_sulfate").setFormula("UO₂SO₄")
    GTMaterials.get("uranyl_carbonate").setFormula("UO₂CO₃")
    GTMaterials.get("tributyl_phosphate").setFormula("(C₄H₉)₃PO₄")
    GTMaterials.get("uranyl_nitrate_solution_compound").setFormula("UO₂(NO₃)₂·TBP")
    GTMaterials.get("ammonium_diuranate").setFormula("(NH₄)₂U₂O₇")
    GTMaterials.get("triuranium_octoxide").setFormula("U₃O₈")
    GTMaterials.get("sodium_aluminum_oxide").setFormula("NaAl(OH)₄")
    GTMaterials.get("aluminium_hydroxide").setFormula("Al(OH)₃")
    GTMaterials.get("fluoaluminic_acid").setFormula("H₃AlF₆")
    GTMaterials.get("aluminium_sulfate").setFormula("Al₂(SO₄)₃")
    GTMaterials.get("dilute_trichlorosilane").setFormula("SiHCl₃")
    GTMaterials.get("trichlorosilane").setFormula("SiHCl₃")
    GTMaterials.get("oxalic_acid").setFormula("H2C2O4")
    GTMaterials.get("plutonium_oxalate_filter_cake").setFormula("Pu??")
    GTMaterials.get("plutonium_dioxide").setFormula("PuO2")
    GTMaterials.get("h3no").setFormula("H3NO")
})